### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by pauldoerwald** [davewasmer/ember-cli-favicon#10]
I just installed this add-on in a basically empty app (it's one of the first things I installed), and it brought live-reloading down to a crawl. It takes 5 seconds every time I make a change before my browser is refreshed, making it essentially unusable during development. My favicon.png is 300x300 and 19kb.

You probably already know about this issue and are working on a solution; I'm adding this ticket so I can track its resolution.

**Comment by davewasmer** [comment]
Thanks @pauldoerwald, I meant to file an issue for this myself and forgot.

Not sure why it's rebuilding the favicons on every rebuild - I would expect it to take ~5 seconds on the initial build (i.e. the first time you run `ember serve`), but not on rebuilds (since the underlying favicon.png hasn't changed). Are you changing your favicon source image at all?

To solve the cold-boot problem, there is [broccoli-persistent-filter](https://github.com/stefanpenner/broccoli-persistent-filter), but that assumes a 1:1 input to output file. This addon is a 1:many filter (a single input favicon.png produces many output files). There is an issue on that repo (stefanpenner/broccoli-persistent-filter#33) to support 1:many, but haven't see any activity on it for a while. I'll post a comment, hopefully we can see what the status is.

**Comment by pauldoerwald** [comment]
My favicon source image is remaining the same through multiple page loads. Good luck getting the problem fixed!

**Comment by cesarizu** [comment]
For me it's taking 30s or more when I add the addon, and recently updating to the 1.0 beta version made it wait for 60s. I don't have a bad internet connection but I suspect it has to do with waiting for the timeout. Disabling the add on makes things very fast.

How can I start debugging this issue?

In the mean time, is there any way to keep it enabled just for production builds?

**Comment by davidjrice** [comment]
Also experiencing this. I'm wondering if it's anything related to using the `postProcessFiles` hook instead of maybe another one (I'm not sure which).
- **with** build takes **10 seconds**
- **without** build takes **< 2 seconds**

This is the slow build analysis output I see during rebuilds. Rebuilds are being triggered when changing any asset. JS, CSS. etc. 

```
Slowest Trees                                 | Total
----------------------------------------------+---------------------
CachingWriter                                 | 10701ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
CachingWriter (1)                             | 10701ms
```

### Environment

```
npm --version
3.8.6
node --version
v6.1.0
```

### dependencies

``` json
{
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.5.0",
    "ember-export-application-global": "^1.0.5",
    "ember-feature-flags": "3.0.0",
    "ember-intl": "2.11.0",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0",
    "ember-validations": "2.0.0-alpha.4",
    "loader.js": "^4.0.1",
    "semantic-ui-ember": "1.0.0"
  }
}
```

**Comment by stefanpenner** [comment]
one thing i noticed so far while debugging whats going on here
-  https://github.com/davewasmer/broccoli-favicon/pull/6 seems to address

**Comment by davewasmer** [comment]
Merged @stefanpenner's PR mentioned above, and released ~~1.0.0-beta.3~~ 1.0.0-beta.4 (botched the beta.3 release, sorry) with the change. That won't improve startup time much (see [my comment about persistent caches](https://github.com/davewasmer/broccoli-favicon/pull/6#issuecomment-227879052) for why), but hopefully it should help rebuild times.

**Comment by davidjrice** [comment]
for what it's worth; startup time seems way improved with this as well; and rebuild time –thank you.

Maybe you haven't had a chance to push it yet, just noticing that I'm only seeing `1.0.0-beta.3` in **npm**, `1.0.0-beta.4` isn't published there (I do see it in the releases here in github however)

**Comment by davewasmer** [comment]
Wow, struggling with the packaging today :wink: should be live now

**Comment by melv-n** [comment]
Does the above mean this issue was addressed? Or should it still be open?

**Comment by stefanpenner** [comment]
@mirague I believe it should be.

**Comment by davewasmer** [comment]
Closing since it appears solved. If not, drop a note and I'll reopen.
