### ISSUE TITLE
icons not rendering on ember-cli-title installation

### ISSUE THREAD

**Issue by KyuubiKeith** [davewasmer/ember-cli-favicon#80]
hey...im new to ember and am starting to get the hang of things, so...I installed ember-cli-title and im not sure what happenned but favicons are not being rendered any more, after uninstalling the title package everything goes back to normal but I dont understand what breaks it, I really want to use them side by side. Any help on this would be appreciated

**Comment by davewasmer** [comment]
@KyuubiKeith welcome to Ember! Glad to have you!

Unfortunately it's tough for me to guess at what might be the issue here. Usually, what's most helpful in this kind of scenario is if you create a reproduction repo.

Basically, create a new Ember app, install ember-cli-title and this addon, and confirm that it breaks. Then publish that repo on Github. This does two things:

1. Confirms that it actually is something in the addon that is breaking ember-cli-title, and not something in your code

2. Gives me an easy way to see the bug in action, which makes it significantly easier to for me to diagnose and fix.

**Comment by KyuubiKeith** [comment]
thank you for giving me a workaround/ a way foward. will be sure to post any problems I get
